### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by shaeinst** [Asabeneh/30-Days-Of-JavaScript#139]
can i use your work for commercial use (with credit)?

**Comment by dnvt** [comment]
Hey, thanks for asking. Sure – Please let met know what you want to use, and how you want you to use it. That would be very appreciated. :) 
You can always drop me [an email](francois@dnvt.me)

**Comment by Asabeneh** [comment]
Hi

We do not allow 30 Days of Python, 30 Days of JavaScript, 30 Days of React
to be used for any kind of commercial purposes. In addition to that, we
don't allow converting the materials to any electronic form (videos, pdf,
publishing on websites, etc).

Thank you so much for asking permission.

Kind regards,
Asabeneh
