### ISSUE TITLE
Day 3 | exercise level 3 question

### ISSUE THREAD

**Issue by gaurika05** [Asabeneh/30-Days-Of-JavaScript#506]
Stuck on this question.
Can anyone help?

![Screenshot (1509)](https://user-images.githubusercontent.com/97402240/189971065-aa99f830-3067-4c29-9fa9-5ca4dd8e61df.png)

**Comment by vansh911** [comment]
let hour = 5;
you may convert check if hour < 10 then convert to string and 
let newhour ="0" + hour;
console.log(newHour)

**Comment by suvrat23** [comment]
Hello gaurika, 
You can use simple if-else statements to achieve the required result.
The code may look like this:
`
let d
      const date = new Date()
      if(date.getMonth() < 10  || date.getDay() < 10)  { 
        d = `${date.getFullYear()}-0${date.getMonth()}-0${date.getDay()}, ${date.getHours()}:${date.getMinutes()}`
      }
      else if (date.getHours() < 10 || date.getMinutes() < 10) {
        `${date.getFullYear()}-${date.getMonth()}-${date.getDay()}, 0${date.getHours()}:0${date.getMinutes()}`
      }
      else {
         d = `${date.getFullYear()}-${date.getMonth()}-${date.getDay()}, ${date.getHours()}:${date.getMinutes()}`
      } `

**Comment by gaurika05** [comment]
ok thanks @suvrat23 got it
