### ISSUE TITLE
Typo in Day 5

### ISSUE THREAD

**Issue by btrezzy** [Asabeneh/30-Days-Of-JavaScript#868]
I am leaving a screenshot to fix it. It should be "are" instead of "ar" in the second line of the paragraph.

<img width="522" alt="Screenshot 2023-09-23 011904" src="https://github.com/Asabeneh/30-Days-Of-JavaScript/assets/128296263/72636dac-f66e-40ce-9166-7de205cd4266">

**Comment by Kunal-Purswani** [comment]
Can I fix this issue?

**Comment by Noman-Nom** [comment]
Can I fix this issue #868
